apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app  # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 80         # The port that will be exposed
      targetPort: 8888  # The port your application listens on
  type: LoadBalancer   # Adjust based on your requirements
