name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set the working
    - name: Build with Maven
      run: mvn clean install -X
      working-directory: ./juvarya
